dm800: use libarachive 3.2.2
In the past we downgrade libarchive to version 3.1.2 to avoid a opkg warning
about timestamps during update dm800.
But now libarchieve 3.1.2 is too old to build against opkg 0.3.6.
Instead of downgrading opkg to 0.3.4, use libarchive 3.2.2 and live
with a warning about timestamps of the packages.

Fix error:
../libopkg/.libs/libopkg.so: undefined reference to `archive_write_set_format_raw'
| collect2: error: ld returned 1 exit status
| make[2]: *** [Makefile:401: opkg] Error 1