enigma2: remove dual tuner letter detection patch
According to tester this patch causing enigma2 crashes.

Backtrace:
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x6B490]
/lib/libc.so.6(__default_rt_sa_restorer) [0xB616FC60]
-------FATAL SIGNAL

IOError: [Errno 16] Device or resource busy
close failed in file object destructor:

Probably due to commit:
https://github.com/OpenPLi/enigma2/commit/d105379b0f67b758a478ce0039c2bb94b28b2dca
Which triggers a segfault now?

This patch is made a long time ago to sync with OpenATV to fix some (cosmetic)
issues with dm780hd.

If dm7080hd really needs this patch, i'll add it back to dm7080hd only.